### ISSUE TITLE
feedback from project site

### ISSUE THREAD

**Issue by martinohanlon** [raspberrypilearning/pacman-terminal#10]
URL: /en/projects/pacman-terminal/5

this is the first pi project i started and it was very informative i only had one question that needed to be answered and that was do i need to go to quarantine folder then delete spooky text to olive ate risk for real viruses or no

**Comment by caitlynraspberrypi** [comment]
Yes, the spooky text file would need to be deleted if it were a real virus, but sometimes not right away! For the challenge at the end, your goal is to do exactly that - get rid of the whole quarantine folder with all the 'virus' files you've collected, to make sure your computer is safe.

**Comment by caitlynraspberrypi** [comment]
Not worth adapting the resource as it seems clear from the project text as is.
