### ISSUE TITLE
Merge conflict text on project page

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/pacman-terminal#13]
Seems like `step_3.md` (also visible at https://projects.raspberrypi.org/en/projects/pacman-terminal/3 ) contains a git merge conflict, which needs to be removed. There's a "«««< HEAD" visible on the page, and large parts of the page are duplicated e.g. "Next to the $ (the shell prompt), type or copy and paste:" appears twice.

**Comment by martinohanlon** [comment]
Thank you @lurch - fixed with #16 :)
