### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/pacman-terminal#4]
## Step 2
- **Suggestion** - Arrange ghost images into a grid

## Step 3
- **Suggestion** - Have them wget the script and then run it, rather than piping to bash/sh. As this is a security resource, I don't think familiarising people to piping unread scripts to bash is a good idea.
- I think the wget link should be `https://raw.githubusercontent.com/raspberrypilearning/pacman-terminal/master/en/resources/pacman_start` to get the actual script rather than the html.

## Step4 
- **Suggestion** - "Here we can see we are in the `pi/` directory." Should probably read "Here we can see we are in the `/home/pi/` directory." It might then need some explanation of `home` though which might be too much.
- Because of my screen resolution - this looks like an unordered list
![cap1](https://user-images.githubusercontent.com/4516338/40826072-6fa0c9e2-6571-11e8-9819-d9d5f95b163f.png)
It's resolved by reducing screensize. Might need to check this as I'm on a pretty standard 1920x1080 monitor, which most people will be using.
![cap2](https://user-images.githubusercontent.com/4516338/40826074-7410b03c-6571-11e8-81fd-8a91c87106d3.png)

## Step 7
- I think the bash script needs altering to download the ghost files as `raw.githubusercontent`, as at the moment they are all html and I can't see the treasure names

Overall - really nice introduction to bash, with the most of the major commands shown. Might be nice to show the `mv` command as well.

Idea - I'd not have the bash script add files directly to their /home/pi directory. Instead just download a single directory called `maze` or something that contains other directories, ghosts and dummy empty directories. This way the resource could be used with MacOS users and other Linux users as well, and not just for those on the Pi.

**Comment by caitlynraspberrypi** [comment]
Changes implemented. Thanks for the feedback! The idea to use on MacOS and other Linux can be implemented later on..
